"""Public API surface of the LIMA audit inventory layer (IP-0016).

Re-exports only the frozen Packet v1.1 (§6 D2) public API; all logic lives
in :mod:`lima.audit.inventory`. IP-0019 appends the semantic prioritizer
Top-N layer re-exports of :mod:`lima.audit.semantic_prioritizer`.
IP-0021 appends the RAM wire schema re-exports of :mod:`lima.audit.ram_schema`.
IP-0022 appends the secret-shaped filename admission re-exports of
:mod:`lima.audit.inventory` as package-namespace re-exports only: the frozen
IP-0021 exact-cap assertion (``test_ram_schema.InitAppendSegmentTests``) pins
``len(__all__) == 54`` with the IP-0021 tail, so ``__all__`` stays verbatim.
"""

from lima.audit.inventory import (
    GAP_BUDGET_EXHAUSTED,
    GAP_INVENTORY_SKIPPED,
    GAP_MANIFEST_PARSE_ERROR,
    GAP_NO_LANGUAGES_DETECTED,
    GAP_UNSUPPORTED_LANGUAGE,
    PROFILE_PROVENANCE_ANCHOR,
    SKIP_REASON_TO_GAP_DETAIL,
    ProfileBudgets,
    ProfileBuildResult,
    ProfileInventoryOptions,
    build_repository_profile,
)
from lima.audit.inventory import (
    is_secret_shaped_path as is_secret_shaped_path,
)
from lima.audit.ram import (
    GAP_AMBIGUOUS_DISPATCH,
    GAP_DYNAMIC_IMPORT,
    RAM_PROVENANCE_ANCHOR,
    PythonRamFacts,
    RamBudgets,
    RamFactsBuildResult,
    RamKeyFlow,
    build_python_ram_facts,
    ram_facts_digest,
)
from lima.audit.ram_schema import (
    GAP_CODES_ALL,
    GAP_EXECUTION_REQUIRED_TRIGGERS,
    PROVENANCE_ANCHOR_CHAIN,
    RAM_WIRE_SCHEMA_FILE,
    RAM_WIRE_SCHEMA_NAME,
    execution_required_from_gaps,
    load_ram_wire_schema,
    ram_wire_digest,
    ram_wire_payload,
    validate_ram_wire_payload,
)
from lima.audit.semantic_prioritizer import (
    GAP_SEMANTIC_MALFORMED_OUTPUT,
    GAP_SEMANTIC_MODEL_OFF,
    GAP_SEMANTIC_MODEL_TIMEOUT,
    SEMANTIC_CATEGORY_CODE_EXECUTION,
    SEMANTIC_CATEGORY_COMMAND_EXECUTION,
    SEMANTIC_CATEGORY_DESERIALIZATION,
    SEMANTIC_CATEGORY_ENTRYPOINT,
    SEMANTIC_CATEGORY_EXTERNAL_INPUT,
    SEMANTIC_CATEGORY_PATH_TRAVERSAL,
    SEMANTIC_CATEGORY_SQL_INJECTION,
    SEMANTIC_CATEGORY_TRUST_BOUNDARY,
    SEMANTIC_CATEGORY_UNRESOLVED_EDGE,
    SEMANTIC_MAX_TOP_N,
    SEMANTIC_PROVENANCE_ANCHOR,
    SemanticBudgets,
    SemanticCandidate,
    SemanticModelClient,
    SemanticOptions,
    SemanticTopNResult,
    SemanticWeights,
    build_semantic_top_n,
    candidate_id,
    semantic_config_digest,
    semantic_result_digest,
)

__all__ = [
    "GAP_BUDGET_EXHAUSTED",
    "GAP_INVENTORY_SKIPPED",
    "GAP_MANIFEST_PARSE_ERROR",
    "GAP_NO_LANGUAGES_DETECTED",
    "GAP_UNSUPPORTED_LANGUAGE",
    "PROFILE_PROVENANCE_ANCHOR",
    "SKIP_REASON_TO_GAP_DETAIL",
    "ProfileBudgets",
    "ProfileBuildResult",
    "ProfileInventoryOptions",
    "build_repository_profile",
    "GAP_AMBIGUOUS_DISPATCH",
    "GAP_DYNAMIC_IMPORT",
    "PythonRamFacts",
    "RAM_PROVENANCE_ANCHOR",
    "RamBudgets",
    "RamFactsBuildResult",
    "RamKeyFlow",
    "build_python_ram_facts",
    "ram_facts_digest",
    "GAP_SEMANTIC_MALFORMED_OUTPUT",
    "GAP_SEMANTIC_MODEL_OFF",
    "GAP_SEMANTIC_MODEL_TIMEOUT",
    "SEMANTIC_CATEGORY_CODE_EXECUTION",
    "SEMANTIC_CATEGORY_COMMAND_EXECUTION",
    "SEMANTIC_CATEGORY_DESERIALIZATION",
    "SEMANTIC_CATEGORY_ENTRYPOINT",
    "SEMANTIC_CATEGORY_EXTERNAL_INPUT",
    "SEMANTIC_CATEGORY_PATH_TRAVERSAL",
    "SEMANTIC_CATEGORY_SQL_INJECTION",
    "SEMANTIC_CATEGORY_TRUST_BOUNDARY",
    "SEMANTIC_CATEGORY_UNRESOLVED_EDGE",
    "SEMANTIC_MAX_TOP_N",
    "SEMANTIC_PROVENANCE_ANCHOR",
    "SemanticBudgets",
    "SemanticCandidate",
    "SemanticModelClient",
    "SemanticOptions",
    "SemanticTopNResult",
    "SemanticWeights",
    "build_semantic_top_n",
    "candidate_id",
    "semantic_config_digest",
    "semantic_result_digest",
    "GAP_CODES_ALL",
    "GAP_EXECUTION_REQUIRED_TRIGGERS",
    "PROVENANCE_ANCHOR_CHAIN",
    "RAM_WIRE_SCHEMA_FILE",
    "RAM_WIRE_SCHEMA_NAME",
    "execution_required_from_gaps",
    "load_ram_wire_schema",
    "ram_wire_digest",
    "ram_wire_payload",
    "validate_ram_wire_payload",
]
